name: Auto-merge release sync PRs

on:
  pull_request:
    branches:
      - release
    types:
      - opened

jobs:
  auto-merge-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge for PR to release
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

