name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  USER: ${{ secrets.DOCKER_USERNAME }}
  REPO: gns3-server  

jobs:
  set_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: version
        run: |
          VERSION=$(sed -nE 's/^gns3-server==(.+)$/\1/p' requirements.txt)
          if [ -z "$VERSION" ]; then
            echo "VERSION not found" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    outputs:
      version: ${{ steps.version.outputs.version }}

  build:
    runs-on: self-hosted
    needs: set_version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          platforms: linux/amd64, linux/arm64

      - name: login to Docker hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: arm64 image build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:${{ needs.set_version.outputs.version }}
            ${{ env.USER }}/${{ env.REPO }}:latest
          push: true
