name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  USER: ${{ secrets.DOCKER_USERNAME }}
  REPO: gns3-server  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: set VERSION
        id: version
        run: |
          VERSION=$(sed -nE 's/^gns3-server==(.+)$/\1/p' requirements.txt)
          if [ -z "$VERSION" ]; then
            echo "VERSION not found in requirements.txt" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@3.10.0

      - name: Login to Docker hub
        uses: docker/login-action@3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: prod
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:${{ needs.dependencies_init.outputs.version }}
            ${{ env.USER }}/${{ env.REPO }}:latest
          push: true
