name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        echo "VERSION=$(sed -e s/gns3-server==//g requirements.txt)" >> $GITHUB_ENV
        echo "USER=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
        echo "REPO=gns3-server" >> $GITHUB_ENV

    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@3.10.0

    - name: Login to Docker hub
      uses: docker/login-action@3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64, linux/arm64
        tags: |
          ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
          ${{ env.USER }}/${{ env.REPO }}:latest
      
