name: Update Dependencies

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
  
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "farwes1180@gmail.com"

      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git status

      - name: Commit and push if changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add dependencies/
            git commit -m "chore: update submodules"
            git push
          else
            echo "No submodule updates"
          fi
